In [732]:
%matplotlib notebook

In [733]:
import nltk
#>>> nltk.download('punkt')

from nltk import tokenize

In [734]:
# Dependencies
import tweepy
import numpy as np
import json
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime
from matplotlib import style

# Import and Initialize Sentiment Analyzer
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

In [735]:
# Import data into pandas from CSV
campaign = "data/presidential-campaign-trail/Election Campaign Trail.csv"
df = pd.read_csv(campaign)
df.head()
#df_new = df.set_index("Candidate")

#df_new

         Candidate       Date                  Location
0  Donald J. Trump  11-Jul-16  Virginia Beach, Virginia
1  Donald J. Trump  16-Jul-16   New York City, New York
2  Donald J. Trump  21-Jul-16           Cleveland, Ohio
3  Donald J. Trump  27-Jul-16            Doral, Florida
4  Donald J. Trump   5-Aug-16      Green Bay, Wisconsin

In [736]:
# Locate all speeches in Ohio
df_ohio = df.loc[df["Location"].str.contains("Ohio")]
df_ohio.head()

          Candidate       Date          Location
2   Donald J. Trump  21-Jul-16   Cleveland, Ohio
8   Donald J. Trump  15-Aug-16  Youngstown, Ohio
16  Donald J. Trump   1-Sep-16  Cincinnati, Ohio
17  Donald J. Trump   1-Sep-16  Wilmington, Ohio
21  Donald J. Trump   8-Sep-16   Cleveland, Ohio

In [737]:
# Find locations in common for speeches in data frame

common_locations = pd.concat(g for _, g in df_ohio.groupby("Location") if len(g) > 1)
common_locations

           Candidate       Date           Location
82   Hillary Clinton   3-Oct-16        Akron, Ohio
186     Barack Obama   1-Aug-12        Akron, Ohio
16   Donald J. Trump   1-Sep-16   Cincinnati, Ohio
97   Hillary Clinton  31-Aug-16   Cincinnati, Ohio
115      Mitt Romney   1-Sep-12   Cincinnati, Ohio
178     Barack Obama  16-Jul-12   Cincinnati, Ohio
223     Barack Obama  17-Sep-12   Cincinnati, Ohio
266     Barack Obama   4-Nov-12   Cincinnati, Ohio
2    Donald J. Trump  21-Jul-16    Cleveland, Ohio
21   Donald J. Trump   8-Sep-16    Cleveland, Ohio
88   Hillary Clinton  21-Oct-16    Cleveland, Ohio
235     Barack Obama   5-Oct-12    Cleveland, Ohio
251     Barack Obama  25-Oct-12    Cleveland, Ohio
47   Donald J. Trump  13-Oct-16     Columbus, Ohio
84   Hillary Clinton  10-Oct-16     Columbus, Ohio
204     Barack Obama  21-Aug-12     Columbus, Ohio
224     Barack Obama  17-Sep-12     Columbus, Ohio
238     Barack Obama   9-Oct-12     Columbus, Ohio
269     Barack Obama   5-Nov-12     Columbus, Ohio
53   Donald J. Trump  20-Oct-16     Delaware, Ohio
150      Mitt Romney  10-Oct-12     Delaware, Ohio
98   Hillary Clinton  31-Oct-16         Kent, Ohio
229     Barack Obama  26-Sep-12         Kent, Ohio
120      Mitt Romney  10-Sep-12    Mansfield, Ohio
187     Barack Obama   1-Aug-12    Mansfield, Ohio
59   Donald J. Trump  27-Oct-16  Springfield, Ohio
259     Barack Obama   2-Nov-12  Springfield, Ohio
83   Hillary Clinton   3-Oct-16       Toledo, Ohio
134      Mitt Romney  26-Sep-12       Toledo, Ohio
213     Barack Obama   3-Sep-12       Toledo, Ohio

In [738]:
# Drop duplicates for candidates who spoke in the more than once
candidate = common_locations.drop_duplicates(subset = ["Candidate", "Location"])
candidate

           Candidate       Date           Location
82   Hillary Clinton   3-Oct-16        Akron, Ohio
186     Barack Obama   1-Aug-12        Akron, Ohio
16   Donald J. Trump   1-Sep-16   Cincinnati, Ohio
97   Hillary Clinton  31-Aug-16   Cincinnati, Ohio
115      Mitt Romney   1-Sep-12   Cincinnati, Ohio
178     Barack Obama  16-Jul-12   Cincinnati, Ohio
2    Donald J. Trump  21-Jul-16    Cleveland, Ohio
88   Hillary Clinton  21-Oct-16    Cleveland, Ohio
235     Barack Obama   5-Oct-12    Cleveland, Ohio
47   Donald J. Trump  13-Oct-16     Columbus, Ohio
84   Hillary Clinton  10-Oct-16     Columbus, Ohio
204     Barack Obama  21-Aug-12     Columbus, Ohio
53   Donald J. Trump  20-Oct-16     Delaware, Ohio
150      Mitt Romney  10-Oct-12     Delaware, Ohio
98   Hillary Clinton  31-Oct-16         Kent, Ohio
229     Barack Obama  26-Sep-12         Kent, Ohio
120      Mitt Romney  10-Sep-12    Mansfield, Ohio
187     Barack Obama   1-Aug-12    Mansfield, Ohio
59   Donald J. Trump  27-Oct-16  Springfield, Ohio
259     Barack Obama   2-Nov-12  Springfield, Ohio
83   Hillary Clinton   3-Oct-16       Toledo, Ohio
134      Mitt Romney  26-Sep-12       Toledo, Ohio
213     Barack Obama   3-Sep-12       Toledo, Ohio

In [739]:
# Find locations in common for speeches by candidates (Must be greater than 4 since there are 4 candidates)
cities = candidate.groupby('Location')['Candidate'].count()
cities

Location
Akron, Ohio          2
Cincinnati, Ohio     4
Cleveland, Ohio      3
Columbus, Ohio       3
Delaware, Ohio       2
Kent, Ohio           2
Mansfield, Ohio      2
Springfield, Ohio    2
Toledo, Ohio         3
Name: Candidate, dtype: int64

In [740]:
speech_city = "Cincinnati, Ohio"

In [741]:
print(f"The city with whom all 4 candidates spoke was Cincinnati, Ohio.")

The city with whom all 4 candidates spoke was Cincinnati, Ohio.

In [742]:
# Placeholder for strings
trump = ""
clinton = ""
romney = ""
obama = ""

# Open each of the samples
with open("data/presidential-campaign-trail/Trump.txt", encoding='utf-8') as sample:
    trump = sample.read()

with open("data/presidential-campaign-trail/Clinton.txt", encoding='utf-8') as sample:
    clinton = sample.read()

with open("data/presidential-campaign-trail/Romney.txt", encoding='utf-8') as sample:
    romney = sample.read()
    
with open("data/presidential-campaign-trail/Obama.txt", encoding='utf-8') as sample:
    obama = sample.read()

In [743]:

# Run Vader Sentiment Analysis on Each of the Samples (Using NLTK for analyzing longer texts)
samples = (trump, clinton, romney, obama)
for sample in samples:
    
    sentence_list = tokenize.sent_tokenize(sample)
    paragraphSentiments = 0.0
    for sentence in sentence_list:
        vs = analyzer.polarity_scores(sentence)
        #print("{:-<69} {}".format(sentence, str(vs["compound"])))
        paragraphSentiments += vs["compound"]
    print("AVERAGE SENTIMENT FOR PARAGRAPH: \t" + str(round(paragraphSentiments / len(sentence_list), 4)))
    print("----------------------------------------------------")

# Loop through Each Sample


    # Run Vader Analysis on each Sample
    #results = analyzer.polarity_scores(sample)
    overall = vs["compound"]
    pos = vs["pos"]
    neu = vs["neu"]
    neg = vs["neg"]

    # Print Samples and Analysis
    
    print("Compound Score:", overall)
    print("Positive Score:", pos)
    print("Neutral Score:", neu)
    print("Negative Score: ", neg)
    print()

AVERAGE SENTIMENT FOR PARAGRAPH: 	0.3585
----------------------------------------------------
Compound Score: 0.7506
Positive Score: 0.787
Neutral Score: 0.213
Negative Score:  0.0

AVERAGE SENTIMENT FOR PARAGRAPH: 	0.1629
----------------------------------------------------
Compound Score: 0.3612
Positive Score: 0.556
Neutral Score: 0.444
Negative Score:  0.0

AVERAGE SENTIMENT FOR PARAGRAPH: 	0.2749
----------------------------------------------------
Compound Score: 0.7035
Positive Score: 0.538
Neutral Score: 0.462
Negative Score:  0.0

AVERAGE SENTIMENT FOR PARAGRAPH: 	0.1517
----------------------------------------------------
Compound Score: 0.891
Positive Score: 0.677
Neutral Score: 0.323
Negative Score:  0.0